### PR TITLE
Exclude yanked releases when choosing baseline version

### LINKED ISSUE #254: Yanked release selected as baseline
The latest matching release from crates.io is selected by `check-release` even if it has been yanked, which results in `error: failed to select a version for the requirement (...)`.

### How to reproduce

- Clone `cargo-semver-checks`.
- Change version in `Cargo.toml` to `0.4.5`.
- Run `cargo run semver-checks check-release`.

### PR DESCRIPTION
**Pull request by mgr0dzicki**
Closes #254

Extracts the selection of baseline version to a separate function, adds tests for it.

### CODE REVIEW

File: src/baseline.rs [hunk 1]
```diff
@@ -340,3 +356,82 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+            "yanked": yanked,
+            "cksum": "00".repeat(32),
+        }))
+        .unwrap()
+    }
+
+    fn new_crate(versions: &[Version]) -> Crate {
+        // `crates_index::Crate` cannot be created explicitly, as its field
+        // is private, so we use the fact that it can be deserialized.
+        serde_json::from_value(serde_json::json!({ "versions": versions })).unwrap()
```
Comment (tonowak) [inline src/baseline.rs:383]: From what I remember, we're trying to use `expect` (or any alternatives with custom error messages) instead of `unwrap` for better debugging messages.

File: src/baseline.rs [hunk 2]
```diff
@@ -340,3 +356,82 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+    }
+
+    #[test]
+    fn choose_baseline_version_yanked() {
+        let crate_ = new_crate(&[
+            new_mock_version("1.2.0", false),
```
Comment (tonowak) [inline src/baseline.rs:389]: Each `new_crate` call is done by passing a list of `new_mock_version`. I wonder, wouldn't it be more concise to pass a list of tuples/structs (`version`, `is_yanked`), instead of a list of objects constructed by passing `version` and `is_yanked`?

This comment is not a request to change anything in the code -- I'm just curious whether this would be more readable/concise and I'm open for discussion.

File: src/baseline.rs [hunk 3]
```diff
@@ -340,3 +356,82 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+    }
+
+    fn new_crate(versions: &[Version]) -> Crate {
+        // `crates_index::Crate` cannot be created explicitly, as its field
+        // is private, so we use the fact that it can be deserialized.
+        serde_json::from_value(serde_json::json!({ "versions": versions })).unwrap()
+    }
+
+    #[test]
+    fn choose_baseline_version_yanked() {
```
Comment (tonowak) [inline src/baseline.rs:387]: This function name is misleading. It is not a yanked version that is being chosen.

File: src/baseline.rs [hunk 4]
```diff
@@ -340,3 +356,82 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+        ]);
+        let current_version = semver::Version::parse("1.2.1-rc2").unwrap();
+        assert_eq!(
+            choose_baseline_version(&crate_, Some(&current_version)).unwrap(),
+            "1.2.0".to_string()
+        );
+    }
+
+    #[test]
+    fn choose_baseline_version_no_current() {
```
Comment (tonowak) [inline src/baseline.rs:426]: This function name is possibly misleading. From the name, I would expect the test to have a `current` version and a list of crates that doesn't have this `current` version.

File: src/baseline.rs [hunk 5]
```diff
@@ -242,6 +243,43 @@ fn create_rustdoc_manifest_for_crate_version(
...
+                anyhow::format_err!(
+                    "No available baseline versions for {}@{}",
+                    crate_.name(),
+                    current
+                )
+            })
+    } else {
+        let instance = crate_
+            .highest_normal_version()
+            .unwrap_or_else(|| crate_.highest_version())
```
Comment (tonowak) [inline src/baseline.rs:277]: I know that this code is unchanged in this PR, but I don't really understand this line -- maybe it could be commented to explain what's going on here @obi1kenobi. What is considered a "normal" version and why it is OK to choose a "not normal" (whatever is "normal") version when there isn't a normal one? Assuming that a "normal" possibly means non-yanked and non-pre-release, what would happen when there are only "not normal" versions?

File: src/baseline.rs [hunk 6]
```diff
@@ -259,30 +297,8 @@ impl BaselineLoader for RegistryBaseline {
         // - Most likely the user cares about the last official release
```
Comment (obi1kenobi) [inline src/baseline.rs:297]: This comment block seems relevant to the code block you extracted into a function. Probably move it there too?

File: src/baseline.rs (hunk 5 above)
Comment (obi1kenobi) [reply src/baseline.rs:277]: Your guess was correct, it's "not yanked, not pre-release": https://docs.rs/crates-index/latest/crates_index/struct.Crate.html#method.highest_normal_version

If there's no "normal" version, then our options are:
- error
- choose the best option from what's available

The choice isn't necessarily obvious, and this isn't my code. But I think the decision to try to "guess what the user wants" in this case rather than making it a hard error is a reasonable one: in the worst case, we error anyway, and in the best case we guess correctly and delight the user.

Leaving a comment is reasonable. It might just restate what the docs for the two methods on `Crate` already say, but that's alright if it saves the next reader of the code a Google search.

**Review by obi1kenobi — COMMENTED** [review]
I'm excited to have test coverage on this tricky logic! Thanks for putting it together.

It would be good to add two more test cases that check & document that when all versions are either yanked or pre-releases, cargo-semver-checks will pick the largest-numbered version regardless of whether it's been yanked or is a pre-release. (One test where it's yanked and one where it's a pre-release.)

File: src/baseline.rs (hunk 2 above)
Comment (mgr0dzicki) [reply src/baseline.rs]: I've done some refactoring to avoid this code duplication in tests, how do you find it now?

File: src/baseline.rs (hunk 3 above)
Comment (mgr0dzicki) [reply src/baseline.rs:411]: I'm not really good at naming thing, what better proposition do you have?

File: src/baseline.rs (hunk 4 above)
Comment (mgr0dzicki) [reply src/baseline.rs:438]: And same question here, do you have some idea how can we name it better?

File: src/baseline.rs (hunk 1 above)
Comment (mgr0dzicki) [reply src/baseline.rs]: Changed all `unwrap`s to `expect`s, please have a look at the messages.

**Comment by mgr0dzicki** [comment]
> It would be good to add two more test cases that check & document that when all versions are either yanked or pre-releases, cargo-semver-checks will pick the largest-numbered version regardless of whether it's been yanked or is a pre-release. (One test where it's yanked and one where it's a pre-release.)

Added! They revealed that my logic of handling yanked versions was not behaving as it should (it was ignoring yanked releases when there weren't any normal one). I fixed this.

File: src/baseline.rs [hunk 7]
```diff
@@ -340,3 +360,104 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+        // are private, so we use the fact that it can be deserialized.
+        serde_json::from_value(serde_json::json!({
+            "name": "test-crate",
+            "vers": version_name,
+            "deps": [],
+            "features": {},
+            "yanked": yanked,
+            "cksum": "00".repeat(32),
+        }))
+        .expect("Parsing JSON as crates_index::Version should not result in any errors.")
```
Comment (tonowak) [inline src/baseline.rs:381]: Something I learned from @obi1kenobi -- this message describes an invariant, but it makes more sense in an error message to describe what failed. So maybe consider writing it as `Failed to create crates_index::Version from a hand-written JSON`.

File: src/baseline.rs (hunk 5 above)
Comment (tonowak) [reply src/baseline.rs:283]: Can you leave a comment here (in this code) in this PR @mgr0dzicki ?

File: src/baseline.rs (hunk 3 above)
Comment (tonowak) [reply src/baseline.rs:411]: What do you think about `baseline_choosing_logic_skips_yanked`?

File: src/baseline.rs (hunk 4 above)
Comment (tonowak) [reply src/baseline.rs:438]: What do you think about `baseline_choosing_logic_without_current_picks_latest_normal`? A bit long, but I don't see any reason to make it shorter.

File: src/baseline.rs [hunk 8]
```diff
@@ -374,64 +374,68 @@ mod tests {
...
-    fn new_crate(versions: &[Version]) -> Crate {
+    fn new_crate(versions: Vec<Version>) -> Crate {
         // `crates_index::Crate` cannot be created explicitly, as its field
         // is private, so we use the fact that it can be deserialized.
-        serde_json::from_value(serde_json::json!({ "versions": versions })).unwrap()
+        serde_json::from_value(serde_json::json!({ "versions": versions }))
+            .expect("Parsing JSON as crates_index::Crate should not result in any errors.")
+    }
+
+    fn test_choose_baseline_version(
```
Comment (tonowak) [inline src/baseline.rs:391]: This function name doesn't tell much.

File: src/baseline.rs (hunk 5 above)
Comment (mgr0dzicki) [reply src/baseline.rs:286]: Done! Please have a look at it @tonowak

File: src/baseline.rs [hunk 9]
```diff
@@ -340,3 +363,113 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+        expected: &str,
+    ) {
+        let crate_ = new_crate(
+            versions
+                .into_iter()
+                .map(|(version, yanked)| new_mock_version(version, yanked))
+                .collect(),
+        );
+        let current_version = current_version_name.map(|version_name| {
+            semver::Version::parse(version_name).expect("current_version_name should be valid")
```
Comment (tonowak) [inline src/baseline.rs:406]: Here you also have `expect`s as invariants.

File: src/baseline.rs [hunk 10]
```diff
@@ -340,3 +363,113 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+        });
+        let choosen_baseline = choose_baseline_version(&crate_, current_version.as_ref())
+            .expect("choose_baseline_version should not return any error");
```
Comment (tonowak) [inline src/baseline.rs:409]: I think it should be `chosen`, not `choosen`?

Comment (mgr0dzicki) [reply src/baseline.rs:410]: definitely ;)

File: src/baseline.rs [hunk 11]
```diff
@@ -340,3 +363,105 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+        // are private, so we use the fact that it can be deserialized.
+        serde_json::from_value(serde_json::json!({
+            "name": "test-crate",
+            "vers": version_name,
+            "deps": [],
+            "features": {},
+            "yanked": yanked,
+            "cksum": "00".repeat(32),
+        }))
+        .expect("Failed to create crates_index::Version from a hand-written JSON.")
```
Comment (tonowak) [inline src/baseline.rs:384]: @obi1kenobi can you describe what exactly should be the format of `expect` messages? I remember that you said that they should start with a small letter and not end with a comma. But also, here it's explained that the string should describe an invariant, not what went wrong: https://stackoverflow.com/questions/66362625/why-is-rusts-expect-called-expect

File: src/baseline.rs [hunk 12]
```diff
@@ -340,3 +363,105 @@ fn need_retry(res: Result<(), crates_index::Error>) -> anyhow::Result<bool> {
...
+                .into_iter()
+                .map(|(version, yanked)| new_mock_version(version, yanked))
+                .collect(),
+        );
+        let current_version = current_version_name.map(|version_name| {
+            semver::Version::parse(version_name)
+                .expect("Failed to parse hand-written string as a valid version name.")
+        });
+        let chosen_baseline = choose_baseline_version(&crate_, current_version.as_ref())
+            .expect("choose_baseline_version should not return any error");
```
Comment (tonowak) [inline src/baseline.rs:410]: Inconsistent style with the rest of `expect`s.

File: src/baseline.rs (hunk 11 above)
Comment (obi1kenobi) [reply src/baseline.rs:384]: This is worth a read: https://doc.rust-lang.org/std/error/index.html#common-message-styles

Definitely lowercase and not ending with punctuation. For the rest, read the doc at the link above and then use your best judgment :)

Comment (mgr0dzicki) [reply src/baseline.rs]: Changed to lowercase without ending punctuation. I used the “expect as precondition” style everywhere, hope it's finally good enough ;)

File: src/baseline.rs [hunk 13]
```diff
@@ -242,6 +243,52 @@ fn create_rustdoc_manifest_for_crate_version(
...
+                anyhow::format_err!(
+                    "No available baseline versions for {}@{}",
+                    crate_.name(),
+                    current
+                )
+            })
+    } else {
+        // If there is no normal version (not yanked and not a pre-release)
+        // choosing the latest one anyway is more reasonable than throwing an
+        // error, as there is still a chance that it is what the user expects.
```
Comment (obi1kenobi) [inline src/baseline.rs:283]: This comment isn't in the right place, and is confusing as a result. Its current placement seems to indicate that it's summarizing what's happening in the entire `else` block. But instead, the comment only applies to the `.unwrap_or_else(|| crate_.highest_version())` part.

I'd make that closure multi-line, and put the comment inside its `{` block instead. Then it's impossible to misinterpret.

Comment (mgr0dzicki) [reply src/baseline.rs]: Definitely good idea, thank you!

**Review by obi1kenobi — APPROVED** [review]
This looks good to me! @tonowak if your concerns are also resolved, let's merge?
